#!/bin/sh
#  Copyright [2013] [Andreas Galazis]
#############################################################################
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at											##
#############################################################################
##     http://www.apache.org/licenses/LICENSE-2.0
#############################################################################
## Unless required by applicable law or agreed to in writing, software	
## distributed under the License is distributed on an "AS IS" BASIS,		
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and	
## limitations under the License.														##
#############################################################################
#sshgenrate 1.0(Avocado) -more portable than which (posix comatible)-
#############################################################################										
use()
{
	eval "$@ < ~/.ssh/id_rsa.pub"
	echo "Go and paste  into the 'Key' field at: Account Settings >SSH Keys>
	      Add SSH key or by pressing Add SSH key after following the link: 
	      https://github.com/settings/ssh"
}

#install the app given as first argument
installapp(){
	if $(testcommand yum) 
	then
   	sudo yum install -y $1 &> /dev/null
   	return 0
	elif $(testcommand apt-get)
	then
   	sudo apt-get install $1 &> /dev/null
    	return 0
	fi
   	return 1
}

#test the existence of a command
testcommand()
{
 	if [ -z "$(command -v $1)" ]
 	then 
  		return 1 #failure nothing returned
 	else
  		return 0 #succes location returned and command works
 	fi
}
#try to find the existence of clipboard copying
#software if it doesnt esxist install it and try
#again to generate the key and copy it to clipboard
trysshgen(){
	if $(testcommand xclip) 
	then
   		cd ~/.ssh
   		ssh-keygen -t rsa -C "$1"
   		use xclip -sel clip
   		return 0 
	elif $(testcommand pbcopy)
	then
   		cd ~/.ssh
   		ssh-keygen -t rsa -C "$1"
		use pbcopy
		return 0
	else
	   echo "Installing xclip..."
		if $(installapp xclip)
		then
			trysshgen
			return 0	
		else
			echo "ERROR:your system is not supported"
			return 1
		fi
	fi
}
trysshgen
